cssh: Refactored code and removed auto-source rcfile functionality

diff --git a/sshWrapper-script/cssh b/sshWrapper-script/cssh
--- a/sshWrapper-script/cssh
+++ b/sshWrapper-script/cssh
@@ -1,9 +1,7 @@
 #!/bin/bash
 
-HOSTLIST="hh- porcupine-"
-FILELIST="~/.bashrc ~/.vimrc ~/.vim/"
-AUTOLOAD_RC_FILE=false
-RC_FILE_NAME=".bashrc"
+HOST_LIST="hh- porcupine-"
+FILE_LIST="~/.bashrc ~/.vimrc ~/.vim/"
 CLEAN_ON_EXIT=false
 
 ########################################################
@@ -11,84 +9,68 @@ CLEAN_ON_EXIT=false
 ########################################################
 
 function error() {
-   printf "ERROR: $@" >&2
+	printf "[ERROR]\t${@}" >&2
 }
 
 function warn() {
-   printf "WARN: $@"
+	printf "[WARN]\t${@}"
 }
 
 function info() {
-   printf "INFO: $@"
+	printf "[INFO]\t${@}"
 }
 
-function expectFile() {
-   if which expect &> /dev/null; then
-      printf "Generating temporary expect file..."
-      printf "#!/usr/bin/expect -f\nlog_user 0\nspawn ssh $@\nsend \"source ~/$USER/$RCFILE\\\n\"\ninteract" > .tmp.$$ && chmod u+x .tmp.$$
-      if [ $? -eq 0 ]; then
-	 printf "Success!\n\n"
-	 ./.tmp.$$
-	 printf "\n"
-	 removeExpectFile
-      else
-         echo -e "Failure!\n\n"
-	 removeExpectFile
-         error "Falling back to regular ssh mode\n"
-	 regularSSH $@
-      fi
-   fi
+function autoSSH() {
+	ssh -o PasswordAuthentication=no -o ConnectTimeout=3 -n ${@} 2>&1
+	return ${?}
 }
 
-function removeExpectFile() {
-   if rm .tmp.$$ &> /dev/null; then
-      info "Cleaned up temporary expect file\n"
-   else
-      warn "Could not remove temporary expect file...Please manually remove '$( dirname $0 )/.tmp.$$'\n"
-   fi
-}
+FILE_LIST=$( eval "echo ${FILE_LIST}" )
+SSH_CREDS=$( autoSSH -v ${@} | sed -n 's/.*\ Connecting\ to\ \(\([[:alnum:]]\+[-.]\?\)\+\)\ .*port\ \([[:digit:]]\+\)\./\1 \3/p' )
+SSH_HOST=$( echo ${SSH_CREDS} | awk '{print $1}' )
+SSH_PORT=$( echo ${SSH_CREDS} | awk '{print $2}' )
 
-function regularSSH() {
-   \ssh $@
-   exit $?
-}
+if [[ -n "${SSH_HOST}" ]] && echo "${SSH_HOST}" | grep -q -e "$( echo "${HOST_LIST}" | sed 's/\ /\\\|/g' )"; then
+	SSH_CREDS=$( echo ${@} | grep -oe "[^[:space:]]\+@\?${SSH_HOST}" )
+	for FILE in ${FILE_LIST}; do
+		if [[ -e ${FILE} ]]; then
+			RMTFILELIST+="$( basename ${FILE} ) "
+		else
+			warn "File '${FILE}' does not exist\n\t\tCheck the FILE_LIST variable in '${0}'\n"
+			info "Continuing on without file '${FILE}'\n"
+			FILE_LIST=$( echo ${FILE_LIST} | sed "s/${FILE}//" )
+		fi
+	done
 
-USER=$( whoami )
-REGEX=$( echo $HOSTLIST | sed 's<\ <\|<g' )
-SSHCREDS=$( echo $@ | grep -E -ow -e "[A-Za-z0-9@]*($REGEX)[-A-Za-z0-9.]*" )
-RCFILE=$( basename $RC_FILE_NAME )
+	info "Copying the specified files over..."
+	ssh -q ${SSH_CREDS} "mkdir -p ~/${USER}/"
+	scp -prq ${FILE_LIST} ${SSH_CREDS}:~/${USER}/
 
-if [ -n "$SSHCREDS" -a -n "$HOSTLIST" ] && ssh -o PasswordAuthentication=no -o ConnectTimeout=3 -nq $SSHCREDS &> /dev/null; then
-   for i in $FILELIST; do
-      if [ -e $( eval "echo $i" ) ]; then
-	 RMTFILELIST+="$( basename $i ) "
-      else
-	 warn "File '$i' does not exist...Check your FILELIST variable in '$0'\n"
-	 info "Continuing on without file '$i'\n\n"
-	 FILELIST=$( echo $FILELIST | sed "s<$i<<" )
-      fi
-   done
+	if [ ${?} -eq 0 ]; then
+		printf "Success!\n"
+		ssh ${@}
+		EXIT=${?}
 
-   if [ -z "$RCFILE" ]; then
-      warn "You haven't specified an runtime config file to be run...check your RC_FILE_NAME variable in '$0'\n\n"
-   elif ! [[ "$FILELIST" =~ "$RCFILE" ]]; then
-      warn "The specified runtime config file will not be run...check that your FILELIST variable in '$0' contains the runtime config file\n\n"
-   fi
-
-   printf "\nCopying a portion of the environment over..."
-   ssh -q $SSHCREDS "mkdir -p ~/$USER/" && eval "scp -rq $FILELIST $SSHCREDS:~/$USER/"
-   if [ $? -eq 0 ]; then
-      printf "Success!\n"
-      $AUTOLOAD_RC_FILE && expectFile $@
-      ! $AUTOLOAD_RC_FILE && printf "Manually source the RC file with the command: \"source ~/$USER/$RCFILE\"\n\n" && ssh $@
-      $CLEAN_ON_EXIT && info "Cleaning up remote files based on your FILELIST variable..." && ssh -q $SSHCREDS "cd ~/$USER/ && rm -rf $RMTFILELIST" && printf "Success!\n" && exit 0
-      $CLEAN_ON_EXIT && printf "Failure!\n" && exit 1
-      exit 0
-   else
-      printf "Failure!\n"
-      error "Falling back to regular ssh mode\n"
-      regularSSH $@
+		if [[ "${CLEAN_ON_EXIT}" == "true" ]]; then
+			info "Cleaning up remote files based on your FILELIST variable..."
+			ssh -q ${SSH_CREDS} "cd ~/${USER}/ && rm -rf ${RMTFILELIST}; cd; rmdir --ignore-fail-on-non-empty ~/${USER}/"
+			if [[ ${?} -eq 0 ]]; then
+				printf "Success!\n"
+				exit 0
+			else
+				printf "Failure!\n"
+				exit ${EXIT}
+			fi
+		else
+			exit ${EXIT}
+		fi
+	else
+		printf "Failure!\n"
+		error "Falling back to regular ssh mode\n"
+		ssh ${@}
+		exit ${?}
    fi
 else
-   regularSSH $@
+	ssh ${@}
+	exit ${?}
 fi
