git-scripts: simplified all scripts and added native coloring

diff --git a/git-scripts/pull-all b/git-scripts/pull-all
--- a/git-scripts/pull-all
+++ b/git-scripts/pull-all
@@ -1,28 +1,13 @@
 #!/bin/bash
 
-if [ "$( uname -s )" == "Darwin" ] && grep -V | grep -q 'BSD'; then
-  function grep(){
-    ggrep "${@}"
-  }
-fi
-
-if [[ -n "${1}" && -d "${1}" ]]; then
-    cd ${1}
-fi
-
-for FOLDER in $( find ${PWD} -maxdepth 1 -type d -not -path ${PWD} ); do
-  if [[ -e "${FOLDER}/.git" ]]; then
-    cd ${FOLDER} || continue
-    OUTPUT=$( git pull 2>&1 )
-    grep -qP '^(Current branch [-[:graph:]]+ is)|(Already) up[ -]to[ -]date.$' <<<"${OUTPUT}"
-    if [[ ${?} -ne 0 || $( wc -l <<<"${OUTPUT}" ) -gt 1 ]]; then
-      NOTE=1
-    else
-      NOTE=0
-    fi
-    pwd
-    echo "${OUTPUT}" | awk -v B=$( tput smso) -v N=$( tput rmso ) -v X=${NOTE} '{ if (X != 0) {print B"\t"$0N} else {print "\t"$0}; }'
-  else
-    continue
-  fi
-done
+set -euo pipefail
+find ${1:-.} -maxdepth 1 -type d -not -path "${1:-.}" -not -path "${1:-.}/\.*" |
+  xargs -L 1 bash -euo pipefail -c "[[ ! -d \"\${0}/.git\" ]] && exit 0;
+    cd \"\${0}\";
+    pwd | awk -v B=$( tput smso ) -v N=$( tput rmso ) '{print B\$0N;}';
+    OUTPUT=\$( git pull 2>&1; exit 0; );
+    echo \"\${OUTPUT}\" | awk -v C=\"\$(
+      { echo \"\${OUTPUT}\" | grep -q \"error\"; } && tput setaf 1 \
+      || { [[ \$( echo \"\${OUTPUT}\" | wc -l ) -gt 1 ]] && tput setaf 3 \
+           || echo \"\"; }
+    )\" -v R=\"\$( tput sgr0 )\" '{ print C\"\t\"\$0R;}';"
